// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGreenhouse.Backend.Data;

#nullable disable

namespace SmartGreenhouse.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007034255_AddActuatorRuntimeTelemetry")]
    partial class AddActuatorRuntimeTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.AiDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirHeaterPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirHeaterReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExhaustFanOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExhaustFanReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FanOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FanReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LightBrightness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LightReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PumpOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PumpReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoilHeaterPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoilHeaterReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AiDecisions");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.ControlRecoveryState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirCoolingActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AirDryingActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AirHeatingActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoilDryingActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoilHeatingActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoilWateringActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantName")
                        .IsUnique();

                    b.ToTable("ControlRecoveryStates");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.PlantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyLightHoursTarget")
                        .HasColumnType("REAL");

                    b.Property<string>("GrowthStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HumidityMaxPct")
                        .HasColumnType("REAL");

                    b.Property<double>("HumidityMinPct")
                        .HasColumnType("REAL");

                    b.Property<bool>("LastAiHadPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAiPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAiResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAiReviewedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdateReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SoilMoistureMaxPct")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilMoistureMinPct")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilTempMaxC")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilTempMinC")
                        .HasColumnType("REAL");

                    b.Property<double>("TempMaxC")
                        .HasColumnType("REAL");

                    b.Property<double>("TempMinC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.Planting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlantedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plantings");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AirHeaterRuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExhaustFanRuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FanRuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HumidityPct")
                        .HasColumnType("REAL");

                    b.Property<long>("LightRuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Lux")
                        .HasColumnType("REAL");

                    b.Property<double?>("PressureHpa")
                        .HasColumnType("REAL");

                    b.Property<long>("PumpRuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoilHeaterRuntimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SoilMoisturePct")
                        .HasColumnType("REAL");

                    b.Property<int>("SoilRaw")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SoilTempC")
                        .HasColumnType("REAL");

                    b.Property<bool>("SoilValid")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("UptimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
