// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGreenhouse.Backend.Data;

#nullable disable

namespace SmartGreenhouse.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831174314_AddAirHeaterSupport")]
    partial class AddAirHeaterSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.AiDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirHeaterPower")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FanOn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LightBrightness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PumpOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoilHeaterPower")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AiDecisions");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.PlantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyLightHoursTarget")
                        .HasColumnType("REAL");

                    b.Property<string>("GrowthStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HumidityMaxPct")
                        .HasColumnType("REAL");

                    b.Property<double>("HumidityMinPct")
                        .HasColumnType("REAL");

                    b.Property<string>("LastUpdateReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SoilMoistureMaxPct")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilMoistureMinPct")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilTempMaxC")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilTempMinC")
                        .HasColumnType("REAL");

                    b.Property<double>("TempMaxC")
                        .HasColumnType("REAL");

                    b.Property<double>("TempMinC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.Planting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlantedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plantings");
                });

            modelBuilder.Entity("SmartGreenhouse.Backend.Models.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("HumidityPct")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lux")
                        .HasColumnType("REAL");

                    b.Property<double?>("PressureHpa")
                        .HasColumnType("REAL");

                    b.Property<double?>("SoilMoisturePct")
                        .HasColumnType("REAL");

                    b.Property<int>("SoilRaw")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SoilTempC")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("UptimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
